---

name: push

on:
 push:

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: test
        run: go test ./...

      - name: vet
        run: go vet ./...

      - name: build
        run: go build ./...
